# Configuración de memoria para el proceso de descompilación de Minecraft
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Propiedades del Entorno
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.18
forge_version_range=[47,)
loader_version_range=[47,)

# Mappings (Usaremos official para máxima compatibilidad)
mapping_channel=official
mapping_version=1.20.1

## Propiedades del Mod: UNTAMED
mod_id=untamed
mod_name=Untamed
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.alejvndro.untamed
mod_authors=Dilan
mod_description=Un mod enfocado en la fauna, implementando animales con comportamientos realistas de caza, huida y ambientación.